# Workflow to build doc, and deploy it using the version as a subdomain.
#
# To run this check locally from the `doc` folder:
#
# .. code-block:: bash
#
#   $ sphinxdoc -v 2 -p $MODULE_DIR -n $MODULE_NAME -o $MODULE_DIR/doc
#   $ cd $MODULE_DIR/doc
#   $ make html-strict
###
name: "DocumentationRelease"

on:
  workflow_dispatch:

env:
  MIN_PYTHON_VERSION: "3.12"

jobs:

  build_and_deploy:

    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false

    permissions:
      contents: write

    steps:
    - name: Extract branch name
      id: extract-branch
      shell: bash
      run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.MIN_PYTHON_VERSION }}
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools matplotlib
        pip install git+https://github.com/AGrigis/pysphinxdoc.git@dev
        pip install --progress-bar off .
    - name: Install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: dvipng texlive-latex-base texlive-latex-extra build-essential
        version: 1.0
    - name: Install documentation resources
      run: |
        DIR=$(pwd)
        which python
        sphinxdoc -v 2 -p $DIR -n hopla -o $DIR/doc
    - name: Compute documentation
      run: |
        DIR=$(pwd)
        cd $DIR/doc
        echo "Documentation folder: $DIR/doc"
        make html-strict
        cd $DIR
    - name: Upload documentation as an artifact
      uses: actions/upload-artifact@v6
      env:
        BRANCH: ${{ steps.extract-branch.outputs.BRANCH }}
      with: 
        name: doc-${{ env.BRANCH }}
        retention-days: 1
        path: |
            doc/_build/html
    - name: Extract module version
      id: extract-version
      shell: python
      run: |
        import os
        import hopla
        with open(os.environ["GITHUB_OUTPUT"], "a") as of:
          of.write(f"VERSION={hopla.__version__}")
    - name: Deploy
      env:
        BRANCH: ${{ steps.extract-branch.outputs.BRANCH }}
        ENV: ${{ steps.extract-version.outputs.VERSION }}
      if: env.BRANCH == 'master' || env.BRANCH == 'main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
        destination_dir: ./${{ env.VERSION }}
